### ISSUE TITLE
Make local static copy of table contents

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/format-support-table#1]
One of the main benefits to having this be a separate repo with its own table rendering is better versioning/approval/tracking of updates instead of everything coming from the live Google sheet

Also makes the event of rebuilding the GitHub pages more obvious (otherwise, I assume you have to manually do it once in a while?)

Anyway, maybe it would also be to our benefit to have a separate copy for each modality since they have different columns (instead of different tabs on the same sheet)

I'd recommend storing content here on this repo as several `.tsv` files

**Comment by garrettmflynn** [comment]
Github Pages will update on every push to the source branch (i.e.`main`). 

I agree, a "local" mode will allow for better control over what is displayed. 

I just pushed an update with local mode enabled. This uses a `.xlsx` reader so we can download a single file for the entire Google Sheet—and since this is more consistent with what is actually returned by Google when I request the remote sheet.

**Comment by garrettmflynn** [comment]
My bad about not breaking this change into a PR. Will do that moving forward in this repo

**Comment by CodyCBakerPhD** [comment]
> Github Pages will update on every push to the source branch (i.e.main).

Perfect


> I just pushed an update with local mode enabled. This uses a .xlsx reader so we can download a single file for the entire Google Sheet

I'm suggesting a simpler format such as `.tsv` so that the GitHub view can render and track the content as text - I don't think it can accurately describe things like diff's on `.xlsx` - was there something about the `.xlsx` structure that was required for your table parser to work as expected?

Basically I'm trying to push the table value content towards the simplest possible representation to decouple it from the rendered visual appearence

**Comment by garrettmflynn** [comment]
You're right, tracking changes isn't possible with `.xlsx`. The reason I'd chosen this format was: 
1. All the tables are held in one file, just like Google Sheets itself. We could separate them there—but that doesn't really have major benefits
2. The parsed structure is more amenable to detecting merged cells since it has some knowledge of formatting.

So if we want to use `.tsv`, we'll have to download each table separately and I'll have to put some extra effort (though there should be appropriate heuristics) into getting the merged cells to be handled appropriately. 

Do you want me to go ahead with that?

**Comment by CodyCBakerPhD** [comment]
> Do you want me to go ahead with that?

I'll put together some basic `.tsv` representations in a PR here tomorrow

I forgot about the cell merging; however, that is entirely stylistic and I'm sure there are other ways of making such a thing look better as opposed to coercing the underlying data (as cells/colors/values) - that was just something I did b/c it was really quick and easy

**Comment by garrettmflynn** [comment]
No worries, I can just download the `.tsv` files and get started. Just wanted to confirm we're alright with those tradeoffs

**Comment by CodyCBakerPhD** [comment]
I suppose I won't be 100% sure until I see what it's like in practice; just trying various approaches right now to try to get a feel for it

**Comment by CodyCBakerPhD** [comment]
Solved by #4
